### ISSUE TITLE
LivePolishTv przestało działać w PVR

### ISSUE THREAD

**Issue by Katapulta** [ramicspa/kodi#292]
Po aktualizacji do Kodi 17.2 czyli najnowszej dostępnej PVR Live TV nie działa - nie da się utworzyć listy ze źródeł ( między innymi tele-wizja ). Wywala błąd dodatku. 

Log z błędu  (sry za obszerność ale nie znam się na programowaniu i językach więc nie wiem co będzie potrzebne )

15:39:58.060 T:3184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'replace'
                                            Traceback (most recent call last):
                                              File "C:\Users\lkoci\AppData\Roaming\Kodi\addons\plugin.video.LivePolishTV\main.py", line 2, in <module>
                                                import zlib, base64; exec(zlib.decompress(base64.b64decode + setki linijek jakichś krzaczków ... 
                                              File "<string>", line 1, in <module>
                                              File "<string>", line 300, in <module>
                                              File "<string>", line 130, in l1l1ll11_tv_
                                              File "<string>", line 109, in l1l11l1l_tv_
                                            AttributeError: 'NoneType' object has no attribute 'replace'
                                            -->End of Python script error report<--
+ znowu setki linijek krzaczków 
                                              File "<string>", line 1, in <module>
                                              File "<string>", line 300, in <module>
                                              File "<string>", line 130, in l1l1ll11_tv_
                                              File "<string>", line 109, in l1l11l1l_tv_
                                            AttributeError: 'NoneType' object has no attribute 'replace'
                                            -->End of Python script error report<--

**Comment by ramicspa** [comment]
spoko, nastepnym razem dla loga uzyj pastebin.com
co do bledu to nie moge go u siebie powtorzyc - na win/lin/android listy m3u tworzone sa bez bledow. Moze przeinstaluj wtyczke

**Comment by linux923344** [comment]
U mnie też się błąd powtórzył

**Comment by Katapulta** [comment]
Jak wyszła aktualka 17.3 - nałożyłem na 17.2 - bez instalacji czystej wersji. Nie dość że LivePolish ładuje mi 94 kanały z tele-wizja ( czyli wszystkie jakie są ) mimo że nie każdy działa to dodatkowo epg mi się "naprawiło" w końcu i zaczęło pokazywać poprawny zakres czasowy. Wcześniej np na 17.1 ładowało mi kanały do PVR ale przykładowo tylko 40... teraz ładuje wszystkie dostępne na tele-wizja i co ciekawe oglądam takie których wcześniej na liście nie miałem a działały na stronie. 

Co do samego Kodi - ja  mam ciągle z nim jakieś problemy - robię uinstall - czyszczę usuwam wszystkie pozostałości, tempy pliki - instaluję na nowo vanila czysty puściutki - i non stop po takim procesie mam błędy przy instalacji różnorakich dodatków... . Czasami kilka razy muszę wywalić kodi z kompa i zainstalować na nowo żeby zaskoczył... 

Ale teraz po aktualce 17.3 odpukać wszystko działa.

**Comment by ramicspa** [comment]
jak widac byl powod dla ktorego szybko wypusci updated z 17.2 do 17.3
