### ISSUE TITLE
musixhub

### ISSUE THREAD

**Issue by Janasek** [ramicspa/kodi#556]
Witam 

Dałbyś radę coś z tego wykombinować?

[http://www.musixhub.com/index.php](url)

**Comment by xxcriticxx** [comment]
raczej nie ja kiedys prosilem o polskie radio

**Comment by Janasek** [comment]
ale to nie radio tylko video całe albumy

**Comment by xxcriticxx** [comment]
@Janasek good luck!

**Comment by tomasiek** [comment]
A IMO to całkiem przyjemna propozycja - fajnie zebrane albumiki w jednym miejscu, o wiele łatwiej wyszukać cały album niż na youtube. Także jestem mocno za.

**Comment by ramicspa** [comment]
wyglada nawet ciekawie, w wolnej chwili zobacze co da sie zrobic

**Comment by Janasek** [comment]
Już sie nie mogę doczekać  ![icon-1 1](https://user-images.githubusercontent.com/25103836/34185883-5d54f430-e528-11e7-8717-b4226af656d4.png)

**Comment by kashkash18** [comment]
Dobry pomysł 🙂

**Comment by Janasek** [comment]
Dzięki za wtyczkę!
teraz tylko kilka poprawek chyba że tylko u mnie to występuje
mianowicie nie przeskakuje automatycznie na kolejny utwór i bak też możliwości w playerze jest tylko przewiń
I jeszcze wyszukiwarka to też by się przydało ale nie jest to priorytet

**Comment by xxcriticxx** [comment]
u mnie z tego serwisu sie nic nie odpala

**Comment by Janasek** [comment]
Dzięki bardzo teraz śmiga jak trzeba nic dodać nic ująć

**Comment by Janasek** [comment]
@xxcriticxx 

zależności pewnie coś ci tam brakuje

**Comment by kashkash18** [comment]
Teraz to jest mistrzostwo :)

**Comment by wisiann** [comment]
male pytanko,
czy mozna zrobic zeby playlista sama oddwarzala nastepne piosenki na liscie?
jakos nie moge znalesc tego ustawienia,

dzieki,

**Comment by xxcriticxx** [comment]
os: libreelec 8.2.2 mr

```
19:52:33.035 T:140266753492736   ERROR: EXCEPTION: argument "url" for method "add" must be unicode or str
19:52:33.037 T:140266753492736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "url" for method "add" must be unicode or str
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.musichubdcom/main.py", line 2, in <module>
                                                import zlib, base64; exec(zlib.decompress(base64.b64decode('eNrtXEtz4siy/i+9mrO5IQnoGx03ZmEaJJAtMRJ6oNqBxEHoYdNjegD9+pP1RFUGjI27z8T0XThkoUdV5Tu/zNJyv0x/+4Rqe5vMbDN9zIxl7WrIiHzfNJ+DONMWujlb1ttkrld5Wrn7afnl81Tvf0fDXp11+trUyg5xWM3SUX+ThmaNvt59GVv7fBHbZTLtdyfrfveh9qvE+FKi6eoxqc0GBYlmH8rvyIqKheFX91+zJzRbPd4H2503s920Mouo9r9nkWnNI9uDucyCMPNiCx3iClXpo59Hw839tNTXSQf+D/1pWFb2NHa38wpto3gzmR9umschGlb7TMsGCyPTg6G9nke+FjzCdauKke6OvSj3I93cBlamR2H+NH/Mv80fM90r9Tgy7QmK7TUynld/TPvPSayvkTVcLQdPq+XXXoli9y9khU+2YeepERru13TTntvcirowr/9Fw8xemDaKI3uILNtflF/2U8PUF7FvpPHmr0xz/5iP7CgI0bOn99dpvO15oe8sHvP9XNt046r/PJ9VTRhVk/FAWy0sc5vUfj4erT7DX3vd62TmVm7hPd5P2/PLqyXMbdJxn5CxtdI4+hPVZhEM9WRhbLTQ6IVI247n5baTRdFsEfW9+cgNwjCL4nrzFNVbC3WQNdX9gx+ZD54WPdw0D8MdTYfITbTqYVranWS2eU6M7I9p5Y+yeL9FVt5POlWDyi+jRNsYWZQlUZnlcdl7mNZusBjZz1FV5cn0Jtl49A2U+1oVZ1H/87xTlVN989mvTbR8jMaLjrmedzb1coTlNBoFnWqeRNnci6NtHGZWUlfwfn+XxOVNspFG/gFpVT8w3Pss3Pi+YZapvjETvforCG1zEeso0VEF8+xMO/k9yEU9NTLT18wirnJ7UUW97BHdL4y9dhtPzNF0VHU9LXuIjC3MxX8I4812UWfmNMrsONR7SbQJp5Z5iOMvk8DMtaWFvqfGJpnq0dd5aE/mFtr4j9Uwqrs30WQ529hTaxvMR7mPIrT3dX8dzfKHaLjX4jA3ok60m5e5job214XZ/xbpbrno+G5U5do8RJO02syjcOMtbrNhCORssjCqaGnm23TkPyxi9+DHthmWvd7U2Hbn+mYfjvo5yOuzF/fQMnZ785HZzGebwTLOvwVhb7swkbOMvZvoMR327LBjlpmhH0AWB5nuJ57hRtMYfV3O/NiLNveZ7j5Es6qYWvZzWvnDyOiVmbUfJiAnaWx/CzvZ7jbbsanmZp6npf2HV24+p0NzPq2jaPnYn/vlF8+Ls0MSRR2wG9q0cv9Mdf8pLHMnq7NxUuqzqI6esvBLvJxVgbe+iS+z6cgfpEb2LYhQf1qZHfAdD0m9D6MYZCPsPaUzhNJyO/eH9rd5xz0EWvVtoVfTJN6P/Ef0dRqh53S4+XYTPbSqXoYbE+l2B1VRnD3mdaj5CdB9k5X+BGm9gz/cbOb1Fzst0bf4Me8gze4sIne8GJkRGlWPvmnXKM417yY79vz7p//JlulTtvzt02L+vPzc/fSvf/3fEkcEc2t02H+17uPS/j6494r6cTUcx+PEOcxRMJr/mTy5D7Pt/t+Pz8XsPuyv+27+77V5GESPv31yCufgDOzSqYcHNBjv3MIxUJFoblEaMJmOYwzheqq7DYhiAfc1q9b9/ZzcN0h3bg33FqnmFHcdp0l7buPskgAVTjNsnMDZu7UDR1TA0Ugafh7Vbu0Zk0FUw3MNGb9xOpMgbZw67LhFAuOO4X1JD94P84H76bwMOId5RGunudPxc47hkeedZiyNC0cYj4xLxodzHRWodIsVHMlz8B6gQXPXuAOn61hDMj/63NXPd/Bz7gDmW+B5SeO/tu7DZIDWbhHCuvHzng7002DdxiRAIJipluD1Y/oH6cEt8HzGPeALrPOuB9fx/IAuY4PMr7hT5316XGu4w3SG9wLfMH3BMDV+BePC/N0SvwcVeDy8vnHXrcd4fBgP7huE6nMF8KVD1t+IeegJkZch5k+PjXfAcgL37el6QM4CB87xOFTeXMuBdcP6gR7wfjxvMZ+EyEP5hudAPgwsp7D+2KP0gvnBuuC+IZ4HkysPy3uH0B3oC+9r4D183I7KDwTrwHxzA5BXoK8Lv1M+vm99k6CfO4MSn+tH/buazkxvpHVdK0c7Nx43icIXuB/kJNQIfRqH/g7jgx7qQEes/2tClwLug/sdup43yMX14wH/dGxngD5wX2K05Jvr4wX9dHMqd3fsvVfJWccl9CphfKxXmF6g58UK+ARHmFeC50veQ37H69HxfCdEblbwPvK7rD/A1wlZ75i9x1PtxGU7U794j0b5SvjZxfKXFNR+yuvE6wP9O8pryx6TIxmX2zs3Bn0YJF04knmCPSPrwHQHfnSxfDmFR/lL+Lo6EDlqrc8heoX1J8F0wfQsBZ0bQc93ynvZsif4/U6HyQnRb6JHV8g9tdvc/r3G3//n68/lK15niNdLriMyXxIPMD0FejXX2dVT8QmRAyw3dF1UfogckbgF1k3HJXzDdqCA9zR32M4R+YH3NcLuFh7V+8bD9p89B+MReqbEj4C/aJ8D31MYF/OHroPFO+z9KawTxzVjoIeN/TGWA+JnHOaXJm+OL1LdKewK0zaJyXE/GfjsnB4ng7sDkSf2nqvlF/gNfIc1go22zIIdS3IcrPbwTixvIKcl5QfMi8nF0b9SPmA5KDH9CT8J/3Hc4bTWeVmuqVzAe+sQbAFO2PDR5Me1w87dmh4nFr0vIed3XTxXMU+sHwGWIybX1F4wPpLfQV5sbF8wfzRsF95Pt2GHHGN+HO/p0azZ7112nrPr/Lxi1w8n77fMNeNDI/iA41SwK5huxC5ie1f88PV15fXZa3benF4vXxeXp2GPrUNrr4PJeyvOvSa/UPSY2CNsh7zb9CqoiF4lhUuPQUSPMTuP+X0Z07eQ6ltRwm+YD0DvAY6nxljuYZ4rsDuYnhBfYnsEcgl2pYvjfJD3Bq9/QvSFxekN4R/N2wbEnuHfG5lO1+Yzx3GIPYL5OTw+I/4T+8cU1k/58Mo8sJ3vUjsGckXsJfHLsG7ip8H+QZwGfsilcaHB8kBjwvLOCctrToxzwHSjfgD4SPQW8igyb/ADMA+Wvyr38XXinBavh9hlzAfqrwoa11+Wp5Uqf5flRfr9wn2GB/HGLfbdbNt5kLOEyBmO2wmdLUwPrJ93Bypv2M6CHW7uYP38dymekPTrtN0ldpy9D9tv4jdZPoX5h+OMN9KL6EVrPq14pZ2fq+9T5ZnHcW9YT4N9Ah9XPnJ64bhtLPAKHAfROBHmReSY6DHRIya3FZ/3FTgIz3NAjk/Ov/X8aX4Q+uP8iti1MdFTyn9pXTROg7iMxkNha31Yj0j+arTm3RrvLL27JG+jcSHQ5+Y4Zcfs5w7n1sxeqvx5g30Dfwb2JSluiysSAx+HPRo3DHsuPe/S68PuJKZHV4kvgA8kvmDjvJMuPo3fqB8Bf8P8TG0zv4PYOfu96LPfM+Z/2HmM2n4Jrufsus/OiT+DsfvtcziS+3UWP+7Z/cfnasTO2fsL/rvZHheuu8p8TWVeih8V6+3T54XfpdcnjC5JUbH5kee1ySA7RRfxnJhfYF6mJ59PYcvzFM/x8ZX1xQodYrNNzx2n+2RQtuKBlt2j/q9keURD8Sast1gusPyMG4f64badOpV/XvA3Ufnu52neQuIqipuQPOgYp9Qh87sYV6PzZ3iR7nD8h8T5CY03aXwG11fYjuVYX6n9/Ij4eqyx40GOq/l1EU935PiTxasWi1Mt/rxdKHF7I8W1PO4d5DmNW+3iFrvD8hWWx8Axlu1LIvKXE3Ikjfua/8B8IXmZTvEAPA8Rj2I51Fi+VtE8luf/4Y7hj12GkxD+H/mM7e8Q538ER/iYePuifql2C64z/a+Z3aLx+u74fKTYoUi2nyy+mljOR+TLuZyn5aWaL7f93DGuOPLttfHU+OEK/l+If1rxumQvTh7VuP+Ir57OB4AmoeYK/GhI5e5j4wnhNyfC37F8zAo5P1n+QvJgjkOwfEGKfy7FGSRf4XiO07ilG49b87yo9xwHezN9Ea3n0HFJPnv1e3oU57C5Pus0fxp3IS+A9+K4VrYnklxiPAHnqcQPeA2+j9nxhtYBz8fx1+CVR9zxLX5teG6+1B81JZ2nEk9fke9dga+e0x+Cq9I6SoPn4eYynaT889p5wXuwXbg7kd/hfD1p5WXp0T5ju074xvFyB+uLRvzwgNcXT/Ob5yfEH1BcF8vLBbshxTMYB+2dycu7WH5BPnZUDxNS30QBsXtwHdd/Mb5L60cYT8XxC+Unef4aeX+TvJ62vwynwHgynSetHxJ/55yzExfyPZofcn/pNgmVr0KlB+dPotH8Dp4zcO2S3E9x7Jf50Wk+tPSwjXPK/kKd/1v9xWv6J+SS8B8ROU2oHLweD9L6I6kjUnvbWkfvgr06Q48XuBGLWzBdP4CeDAeB9/0S9DqNH7xiN0/YndN4x2v45Wl716rrvSuevbkuEo977LhjeYLBjrqUb4hzlm8Eqx17T83yj51SDzgoOHou12HyWsSVt8WrJZvfXp4nX4eYx0GqU4h5lLsWft+OK9v5YgtfVu3om/xuq1/gcr7z1nGSJlrfksdRvMjMHVaHQjE9Jux3ih+Za4eer3kdi/+esOf4dTdW6lnk97ueE3wA3kTj5CP+wnGRIpfzrULCg/YK/gP5lSnjOYWC9wSRgg9RfGRC1iDw6wr3aV3AZ1/Yh9fiuXfiCUyPbaZ/XC/sWsEDDpKeiDpW2ZzWg3acROq+GsZjHZrjnsRnrq57XeEfcK0AP0fv81gdEMYndXDWVxQcn7+tDs3lRsExBR7pKvm8K8sHx/GEfEXye4Q8Ku8X8qzgjoEp43GBx/G4G/FaFUc0ZT3h+KzAae03zjP8uLq98E8Mjzj6l52Efx39Fb+uS/gZ91PCzyl4mcVwMoGrMX0Z4F6L23EyUe83pHr/WhwNpS/g5Dm8h92fxFL/AMffhJ0lOcEJvIb7n5M4GI2feF9aI9uj1/CFy/kZ76tzgnY8dMf6FN8yzm18YHQW9KT+667H6yCTgPe3UPziEl6B40lqd4ai35HhFbg+ffiQ/gTwOdLREvpRS30WQVXK+G7Z+xB8l+O5jE6J8N8J7+u8iMMc4x2C29J+VFI3gDid1NVTko8kJE9c3Y5bBquDrM/cTnBcndsLtb9j3FHi4A6jayHh9Ee7xPtjdnJcKeyLIeOp3M9Wa8EXLi8DT0MF7mUYagnuQzMcgl/g/gaw+bivDl8/uINQcxpv7waORvIjjJfw/rUBy89x/9ZRLqk/P6+X/4U4hdvxscIPHr+o+cRQk6+LegnnR6XwcS/18wh9sZX8oypei3cu1KX/DvJeMHmX6cDpy+VOxH0if1PqQoJuXalOFFSyXgh7w+h4Xi96Ep3574Oq/MXlvlToXshxjVrH4/mriHvq0/oh7Bl7r83ozvky1mW/ADnMB8l9y69c249zRf3tPXXa2+MBl8dRUh+mKfJing/zcxpn9VneK+qe/Pk1z4v5e1h+LN7P82ORLxvt349xHBL104+o04rxxDrY72L99Ai29k3zxHL1EXm9Uj9V6508rxLnlZy3i/xdORd9E9Hp/J7X3UQ/5PDj6qjC3vJznp9zP6bkM7HynCX0upLzem5fmV+0yJxP6PVb6y1vyeMv4frt+LCV7w+4X3zDOLfxYa34MU63I95Rh1J992JdUeQxrE+c+itMP3h+fCP+4Er59kT0myHp+kTu8xH9aAnHBz4CT+X5rzXUhd+W/OtZvnN5K0g9gODazN+T/Re0X3ZC+jFv7bdg/Q+8v4v3YcW+TE8VhxG/8/4KFSfst/HE3REP8ZW+rkjqf2N4yE70c/B5BAnni4hv3IFfu4GnOQHEPZbTSRoeJ3o98HlgG/D1McQ7XgPxkQ7xD66jHcg+U7q/RGN9zwWOS1r5de/qetvLeOc1PPo2vFbQP5Lprva7cBz3BQ5VyeeiP89W+mL8k/0xSZCe7Gc701ei7Pc51995Tdz4N8U7f1S/ksDj3VO4+xH/DBQ/LvpB+XH1QXin2g+p4q8KDhoruGyRKXb2TF8k6CXtkzjFZ9pnIfY3NzxuvbqOeE3/w9+uriTiXr7viceVUrzZwpkovkT7jYywgbzhmr6uN/aD39pn/d76FxyLk7jsDfWWa/YX/dS6spLnCnyno+S15ck6rcBpVHxfxHGNjN+bMl5vmWdwHfJ9BrJflsYnon/r1f0hH6GXbsFwYba/0yX7fFO2P3T1EXHQfmKxvnMLsf2Uebu/8Gi/Yu/cvoUPiBPeiyuofWbX5B+rE/1lr/eDUtyA9qs4MO5RT+TfxfdG6lBX+xqBXxXdr4f3eXu34/wijzMrHm+zPkiyD5XvBxTfnbiyf4Xul2Z9ow1EEQOw5y/33cj0k/pdVbl9mR+d2d9Gx23Sc/sCSXxFvmdA7Bt7HvvNGu+bTg607+K4v+gyXem+aio/7f28pJ4FR7+i39Xg+/KlPinWh3TlvE7u+3vZX3eCHxf7iM7vD7rmPsIX2ofF+wCJfpD9h3RfLc3LSnzdHYi8lfUVk/wf9/n1PgJXm8RKP4lS1+R9JTwecJQ44Ih7EXq92F8l78skfrIhfWSkD430UbK+Hbxu/p0AZT/rVXS9GPef3X9y1X2EP3bV/n4Q37/qUn90Qp5B/w3vHd/zOREPq30v5/K0WtnHWbB9+f9oPZL2M7xWF7isZ8S/HO32bTiWiJe6Z3BEtc7Tkb+DMGbfP3jRl23Q7/Wg8uifyX5t+j0M4n9EnGQ4fB+H/B2L6+T+ZRz7at6CguvuI/rzUv/O8RnHHTqTR9oXMWh9X4d9v+sD8oVj30Et5weJ0gci6g5yfiHsJJLvF/i9XHfg/Sb9Nft+xD/bfr6MDy7IB8nD8fwKanfR+mfIAc8XnVjyhyIPFnyMP5j/zS/F/1f3Ef63+K/U2472IJb5yfu6OB9dVmd0B78KH1/1iz/Fbk8U/VP1TNSBazmuFd/zieX7lbowf47Xlde8nsr4vnaDX4ff1/RdnPg+0I+PkznuLerQSn3iTP9rUiS/SnzM7/978u8F7m8q/dcVq+eZDCdDbfzs2A9QpL9QvnMBNyc4D6a3Q/dH1+OfmPeIvOYg7/cR/Wj0vqBkfZvljvXHKfuAxPe7eL9m9xfKh35AfPQDcW3leyui76Ewz+zHqJT6L69Tqva5PPvdnn94PHXWPrf4WbxZz38gjnhm38SLOpu8f+KY//B+9V8H73gd92j7WdKnfErfvd9/xx9z/w9rPLPA')))
                                              File "<string>", line 1, in <module>
                                              File "<string>", line 133, in <module>
                                              File "<string>", line 215, in l1l1llll1l1_mh_
                                            TypeError: argument "url" for method "add" must be unicode or str
                                            -->End of Python script error report<--
```

**Comment by wisiann** [comment]
nic nie dziala ,trzeba spojrzec w wolnej chwili,

**Comment by tomasiek** [comment]
U mnie działa

31.12.2017 6:50 PM "wisiann" <notifications@github.com> napisał(a):

**Comment by wisiann** [comment]
a u mnie dalej nie?

"one of more items failed.....etc...

zrobilem update recznie i dalej kicha ,
@tomasek..jakes extra ustawienia?

**Comment by tomasiek** [comment]
No i u mnie też juz nie działa...

**Comment by xxcriticxx** [comment]
ping @ramicspa update potrzebny
