### ISSUE TITLE
Filmwebbooster Brak dostępnych źródeł

### ISSUE THREAD

**Issue by klosiu** [ramicspa/kodi#654]
Dzień dobry,
od dziś mam kłopot z wtyczką filmwebbooster. Po wybraniu dowolnego filmu pojawia się komunikat Brak dostępnych źródeł. Żeby było śmieszniej, to przed tym komunikatem pojawia się prośba o sparowanie przez olpair. Czyli coś tam znajduje.
Jestem pewny, że źródła są, bo przez chroma, czy firefox normalnie znajduje i mogę je oglądać. Co więcej nie działają odcinki serialu, które oglądałem wczoraj i działały. Wtyczka działała bez problemu tygodniami. Nie mam żadnych aktualizacji od wczoraj robionych.
Sprzęt to raspberry pi 3 z libreelec najnowszym. Był cyrk z instalacją wtyczki, więc jest postawiony od zera tylko libreelec, tylko repozytorium i tylko dwie wtyczki cda i filmwebbooster + zależności, które się zainstalowały po drodze. Można więc wszelkie konflikty wykluczyć.
Oprócz tego, widziałem w jakiś starszych zgłoszeniach, że po wyborze pozycji do odtwarzania pojawia się lista źródeł. U mnie nigdy się nie pojawia taka lista, nawet jeżeli na filmdb dany film ma źródeł więcej (np. 3 na openload). Tak ma być w aktualnej wersji, czy mam coś nadal źle zainstalowane/skonfigurowane?
Internet działa, bo wtyczka cda działa bez kłopotu.
Jak trzeba dosłać jakieś logi, dodatkowe info, to proszę napisać. Nie udało mi się znaleźć jakie dane są wymagane do zgłoszenia w tym projekcie, więc opisuję co mi do głowy przychodzi.

**Comment by xxcriticxx** [comment]
mam ten sam problem

**Comment by tomasiek** [comment]
Potwierdzam.
Przykład - Avatar z boxoffice - logi:
`6:41:30.625 T:139936049121024  NOTICE: URLResolver: Initializing URLResolver version: 4.0.17
16:41:45.948 T:139936049121024   ERROR: URLResolver: SSLError Error - From: openload Link: http://openload.co/f/3j3LZYdVUZo?Lektor: ('The read operation timed out',)
16:41:46.096 T:139936623749184  NOTICE: VideoPlayer: Opening:`

Jak widać - problem nie jest we wtyczce i w wyszukiwaniu, tylko urlresolver coś nawala. (film pod linkiem jest)
Co do większej ilości źródeł - kiedyś tak było, ale "umowa" współpracy pomiędzy filmwebbooster a ramicspa zakłada tylko wyświetlanie jednego źródła.

**Comment by tomasiek** [comment]
Przy wydłużeniu czasu dla curl w advancedsettings w logach jest:
`16:54:14.525 T:139928172205824 WARNING: URLResolver: Stream UrlOpen Failed: Url: https://1fhjlpe.oloadcdn.net/dl/l/7NE7cmEwCSdENjV1/3j3LZYdVUZo/Avatar.mp4?mime=true HTTP Code: 500 Msg: Internal Server Error (ENCODED)`
Także jak dla mnie to coś z openload - a na tym serwisie opiera się w 99% filmwebbooster.

**Comment by kopernik1983** [comment]
na boxfilm bodaj log tez jest podobny

**Comment by tomasiek** [comment]
Ale ciekawostka - ta sama sieć, te same ustawienia - na boxie mi działa, na linuxie nie...
box:
18:06:03.604 T:3857314720  NOTICE: URLResolver: Initializing URLResolver version: 4.0.17
18:06:08.082 T:4098512992  NOTICE: VideoPlayer: Opening: http://34.download.real-debrid.com/d/GM5WSXOJUGUXK/Avatar.mp4
18:06:08.082 T:4098512992 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:06:08.947 T:3857314720  NOTICE: Creating InputStream

linux:
18:05:36.140 T:139811718559488  NOTICE: URLResolver: Initializing URLResolver version: 4.0.17
18:05:38.177 T:139811718559488 WARNING: URLResolver: Stream UrlOpen Failed: Url: https://oql95q.oloadcdn.net/dl/l/wY5PSHQyWd4jLsXA/3j3LZYdVUZo/Avatar.mp4?mime=true HTTP Code: 500 Msg: Internal Server Error (ENCODED)
18:05:39.215 T:139813485783104  NOTICE: VideoPlayer: Opening:
18:05:39.215 T:139813485783104 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:05:39.216 T:139811330807552  NOTICE: Creating InputStream
18:05:39.216 T:139811330807552   ERROR: CVideoPlayer::OpenInputStream - error opening []

**Comment by xxcriticxx** [comment]
@tomasiek problem tylko na librec?

**Comment by kopernik1983** [comment]
na boxie z real debrid otwierasz dlatego ci dziala

**Comment by tomasiek** [comment]
Nie. Na libreelec jest ok. Na archiwalnych problem, ale tam nie
korzystam... Więc to nie problem że jest problem.

25.02.2018 6:29 PM "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
O fakt... Nie pomyślałem...

25.02.2018 6:32 PM "Tomasz Woś" <tomasz.wos@gmail.com> napisał(a):

**Comment by klosiu** [comment]
> Co do większej ilości źródeł - kiedyś tak było, ale "umowa" współpracy pomiędzy filmwebbooster a ramicspa zakłada tylko wyświetlanie jednego źródła.
Ok, dziękuję.

**Comment by kopernik1983** [comment]
z efilmy 
18:39:28.793 T:5932  NOTICE: URLResolver: Initializing URLResolver version: 4.0.18
18:39:36.650 T:4060  NOTICE: Previous line repeats 1 times.
18:39:36.650 T:4060  NOTICE: script.module.metadatautils --> Rate limiter active for omdbapi.com - delaying request with 2 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
18:39:44.381 T:4676  NOTICE: script.module.metadatautils --> Rate limiter active for omdbapi.com - delaying request with 1 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
18:39:50.461 T:3828  NOTICE: Previous line repeats 1 times.
18:39:50.461 T:3828  NOTICE: URLResolver: Initializing URLResolver version: 4.0.18
18:39:52.099 T:2372  NOTICE: VideoPlayer: Opening:
18:39:52.099 T:2372 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:39:52.099 T:2372   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
18:39:52.099 T:2372   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
18:39:52.100 T:5168  NOTICE: Creating InputStream
18:39:52.100 T:5168   ERROR: CVideoPlayer::OpenInputStream - error opening []
18:39:52.100 T:5168  NOTICE: CVideoPlayer::OnExit()
18:39:52.100 T:2372   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.efilmy/?foldername=Facet+na+miar%C4%99+%5BCOLOR+green%5D+Lektor+PL+%5B%2FCOLOR%5D&page=1&ex_link=http%3A%2F%2Fwww.efilmy.tv%2Ffilm%2C29970%2CFacet-na-miare-2016-Lektor-PL.html&mode=getLinks]
18:39:52.100 T:2372  NOTICE: CVideoPlayer::CloseFile()
18:39:52.100 T:2372  NOTICE: VideoPlayer: waiting for threads to exit
18:39:52.100 T:2372  NOTICE: VideoPlayer: finished waiting
18:39:52.100 T:2372  NOTICE: CVideoPlayer::CloseFile()
18:39:52.100 T:2372  NOTICE: VideoPlayer: waiting for threads to exit
18:39:52.100 T:2372  NOTICE: VideoPlayer: finished waiting
18:39:58.666 T:4060 WARNING: script.module.metadatautils --> Traceback (most recent call last):
                                              File "C:\Users\Marcin\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\utils.py", line 114, in get_json
                                                response = requests.get(url, params=params, timeout=20)
                                              File "C:\Users\Marcin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 72, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "C:\Users\Marcin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 58, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "C:\Users\Marcin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 508, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\Marcin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 618, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\Marcin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 521, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPConnectionPool(host='www.omdbapi.com', port=80): Read timed out. (read timeout=20)
18:39:58.666 T:4060   ERROR: script.module.metadatautils --> ERROR in helpers.utils ! --> HTTPConnectionPool(host='www.omdbapi.com', port=80): Read timed out. (read timeout=20)

**Comment by kopernik1983** [comment]
ogolnie sporo wtyczek jest padnietych

**Comment by tomasiek** [comment]
Może to nie wtyczki tylko urlresolver i komunikacja z nim?

**Comment by kopernik1983** [comment]
byc moze. ale u ciebie widze 0.17 a skad ja mam 0.18

**Comment by xxcriticxx** [comment]
@kopernik1983 no clue

**Comment by kopernik1983** [comment]
pewnoo z jakiegos badziewa :)

**Comment by tomasiek** [comment]
Z qwer... Albo mrblamo. Dla mni to problem z openload. Ten sam link jest wypluwany do urlresolver. Jak mam rd to urlres wybiera ten który ma w cache, jak nie to ten sam link musi obsłużyć bez RD, czyli konwertuje go przez openload żeby wypluło link do filmu bezpośredni. I tu jest problem.

**Comment by xxcriticxx** [comment]
@tomasiek bys zakupil mi gdzies rd kase odam paypalem

chyba ze polecisz jak service co karty z us dzialaja

**Comment by tomasiek** [comment]
http://allegro.pl/paysafecard-10-euro-psc-10e-od-firmy-24-7h-i7031952350.html
Ja to tak załatwiłem...

**Comment by kopernik1983** [comment]
ekino.tv tez wyrzuca bląd tak jak ekinomaniak , wiec jakis chyba problem troche wiekszy z tymi wtyczkami. ale stare poczciwe alltube dzidziala jak trzeba

**Comment by xxcriticxx** [comment]
@kopernik1983 serialosy I ekinomaniak strong dead przynajmniej z usa

**Comment by tomasiek** [comment]
Sprawdziłem, przy wyłączonym RD faktycznie nie znajduje źródeł.
Alltube - to klasa sama w sobie. Dodaj CDA, dailymotion, monthy-python, TVP + lista m3u wiemy skąd i nic więcej nie potrzeba.

**Comment by kopernik1983** [comment]
problem jest jednak z openload , ze spidvid tez takie logi wywala jak z openload. lista jest kapitalna poprostu. po dzie dzisiejszy sie ciesze ze sie na nia zalapalem na samym poczatku :)

**Comment by xxcriticxx** [comment]
Poczatku czego?

**Comment by tomasiek** [comment]
Mi nie pozwala na parowanie z openload... Cały czas please wait.
@xxcriticx lista która jest Wspaniała Ogromna Jedwabiście Totalna Uniwersalna. Czasem na wykopie jest losowanie...

**Comment by kopernik1983** [comment]
Czasami tak jest , zauwazylem najczesciej przez mozille. o dziwo na operze w zasadzie dzialalo lepiej . nie wiem czemu.

**Comment by xxcriticxx** [comment]
Panowie ja nie rozumiem oco wam chodzi?

**Comment by kopernik1983** [comment]
jak nie wiadomoo o co chodzi to chodzi o pieniadz hehehhe :)

**Comment by tomasiek** [comment]
@xxcriticxx lista Wspaniała Ogromna Jedwabiście Totalna Uniwersalna. Najprostszy szyfr...

**Comment by kopernik1983** [comment]
@xxcriticxx jest taka lista m3u z pewnego fora nawet full hd. smiga jak talala. i znowu off top @tomasiek teraz dopiero zauwazylem heheh

**Comment by xxcriticxx** [comment]
Blah damy rade bez listy
